# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

[build]
# The command that builds your application
cmd = "go build -o ./tmp/main ./cmd/main.go"

# The binary file that the build process creates
bin = "tmp/main"

# Customize binary.
full_bin = "APP_ENV=development ./tmp/main"

# Include file extensions to be watched
include_ext = ["go", "tpl", "tmpl", "html"]

# Directories to exclude from watching
exclude_dir = ["assets", "tmp", "vendor", "venv", "build", "dist"]

# Log file for air
log = "logs/air.log"

[log]
# Show log time or not.
time = false

[color]
# Customize each part's color. If no color is found, use the default white.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete binary after air ends.
clean = true
